### ISSUE TITLE
Some names wrong in EN Translation

### ISSUE THREAD

**Issue by Lordben-wan** [ProjectSky/MoreBuilds#15]
During translation to portuguese, I noticied some issues with **English translation**, please check when you have time.

(Actual name in game) ► (How I changed)

CHANGED
Beige Wooden Chair ► Brown Wooden Chair
Brown Wooden Chair ► Beige Wooden Chair
Powder Blue Armchair ► White Armchair
Powder Blue ► White
Gray Counter ► Metal Counter
Gray Corner ► Metal Corner
Theatre Storage ► Theatre Popcorn Storage
White Stairs ► Dark Brown Stairs
White Wooden Motel Stairs ► Brown Stairs
Gas-2-Go Counter ► Gas-2-Go Corner
Square Beige Table ► Beige Square Table
Brown Office Tabl ► Brown Office Table

CANT CHANGE (didn't find option in translate files)
Long Table ► Long Dark Wooden Table
Long Light Table ► Long Light Wooden Table
Long Dark Table ► Long Brown Table

**Comment by ProjectSky** [comment]
fix in next version
