### ISSUE TITLE
Customize construction materials

### ISSUE THREAD

**Issue by pangolp** [ProjectSky/MoreBuilds#16]
Hello, good evening. First of all, I have used the mod, and the truth is that it is a great job. However, I was wondering, if it is possible to make, that the materials that some of them ask for, were different, given, that in some occasions, certain elements, are cheaper to build, than the official ones, and that makes the game a little unbalanced.

I am initiating in the development of mods, so if possible, I would like to collaborate with you in this new implementation. However, when trying to access the information of some methods, I find little documentation, which makes it a little difficult for me to understand some things yet.

I have participated in some open source projects. I've used Lua a little bit, in the World of Warcraft addons, but not really too much yet. That's why I was interested in learning a bit more about it.

Hopefully, I can help you in the expansion of the mod.
Greetings.
Walter.

Pd. I leave you my discord: Stevej#5879

**Comment by ProjectSky** [comment]
I don't have time to update this mod at the moment
the main thing right now is a performance issue with ISContextMenu
anyway, glad to hear someone can help maintain this mod
I will add your discord later

**Comment by pangolp** [comment]
> I don't have time to update this mod at the moment the main thing right now is a performance issue with ISContextMenu anyway, glad to hear someone can help maintain this mod I will add your discord later

Ok, I am waiting for your message. I'm learning a bit about mods, and if I can help, I'm here to do it.

**Comment by Themasterlag2003** [comment]
Why I am here? XD I made the esp translation

**Comment by pangolp** [comment]
> Why I am here? XD I made the esp translation

I don't know how you got here, but welcome.
Make yourself comfortable.
