### ISSUE TITLE
I want to translate your mod to Brazilian Portuguese!

### ISSUE THREAD

**Issue by reinaldogpn** [ProjectSky/MoreBuilds#17]
Hi there!
I've been interested on translating your mod to my language (PTBR) but I'm kind of starting on this translation thing. Any tips on how can I do this? :)

**Comment by ProjectSky** [comment]
PTBR already exists, heck here https://github.com/ProjectSky/MoreBuilds/tree/main/media/lua/shared/Translate/PTBR

**Comment by reinaldogpn** [comment]
Great, I will use it. Looking forward to see it updated on steam, love this mod!
